### ISSUE TITLE
Do not panic on bad messages logged

### ISSUE THREAD

**Issue by kgrech** [Absolucy/tracing-oslog#1]
The code has the following logic [here](https://github.com/Absolucy/tracing-oslog/blob/main/src/logger.rs#L146):
```rust
let message =
	CString::new(message).expect("failed to convert formatted message to a C string");
unsafe { wrapped_os_log_with_type(self.logger, level, message.as_ptr()) };
```

Rust and C store strings differently. Rust stores the string length separately instead of having trailing ``\0`` in the end. As a result, rust allows having unprintable ``\0`` inside the strings.  However such strings can't be converted to C string unless 0 is stripped out.

If you try doing something like ``error!("Hello\0World")``, the IOS application crashes. This is especially critical when logging the data received over network or entered by user.

**Comment by Absolucy** [comment]
Fixed by https://github.com/Absolucy/tracing-oslog/pull/2
